-- CreateEnum
CREATE TYPE "Section" AS ENUM ('COMMUNITY', 'FEEDBACK', 'TUTORIAL');

-- CreateEnum
CREATE TYPE "Subject" AS ENUM ('DIGITAL', 'TRADITIONAL', 'STYLIZED', 'REALISM', 'SKETCHES', 'PORTRAITS', 'CHARACTER_DESIGN', 'FAN_ART', 'PAINTING', 'ILLUSTRATION', 'CONCEPT_ART', 'SCI_FI', 'FANTASY', 'ANIME_MANGA', 'OTHER');

-- AlterEnum
ALTER TYPE "Role" ADD VALUE 'EXPERIENCED';

-- AlterTable
ALTER TABLE "Upload" ADD COLUMN     "mature" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "section" "Section" NOT NULL DEFAULT E'COMMUNITY',
ADD COLUMN     "subjects" "Subject"[],
ADD COLUMN     "thumbnail64" TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" SET DEFAULT E'CASUAL';
